### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by tarushvkodes**
added embed

### CODE REVIEW

**Comment by tarushvkodes** [comment]
do you add it? is It gud?

**Comment by emilydaemon** [comment]
instead of an embed, i think an external page for it and a link there would be a better choice.

**Comment by tarushvkodes** [comment]
ok

**Comment by niilasoika** [comment]
in my opinion closing this would be a good idea @StudioChew

**Comment by tarushvkodes** [comment]
closing what?

**Comment by niilasoika** [comment]
The pull...? @StudioChew @03172008

**Comment by niilasoika** [comment]
up

**Comment by niilasoika** [comment]
CLOSE THIS FREAKING MORE THAN 0,5 MONTHS OLD PULL EEE

**Comment by emilydaemon** [comment]
ok

**Pull request closed without merging**
